import '@/app/styles/globals.scss';
import type { Metadata } from 'next';
import { fonts } from '@/app/config/fonts';
import { cn } from '@/shared/lib/utils';

import { ThemeProvider } from '../ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // suppressHydrationWarning on <html> is necessary to avoid warnings from ThemeProvider, since it updates <html>
  // suppressHydrationWarning applies one level deep, so it won't block hydration warnings on other elements
  return (
    <html
      lang="ru"
      className={cn(fonts.manropeSans.variable, fonts.geistMono.variable, fonts.inter.variable)}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
