import '@/app/styles/globals.scss';
import type { Metadata } from 'next';
import { Geist_Mono, Inter, Manrope } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import { cn } from '@/shared/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const manropeSans = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // suppressHydrationWarning on <html> is necessary to avoid warnings from ThemeProvider, since it updates <html>
  // suppressHydrationWarning applies one level deep, so it won't block hydration warnings on other elements
  return (
    <html
      lang="ru"
      className={cn(manropeSans.variable, geistMono.variable, inter.variable)}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
